In [88]:
import numpy as np

In [89]:
arr = np.array([[[1,2,3],[4,5,6]] , [[1,2,3],[4,5,6]] , [[1,2,3],[4,5,6]]])  # 3-D Array

In [90]:
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [91]:
arr.shape  # shape -> (3, 2, 3) ----> 

(3, 2, 3)

In [92]:
arr.ndim

3

In [93]:
arr[1, 0, :]  #[Table_position , Row_position, Column_position]

array([1, 2, 3])

In [94]:
arr[1, 0, 2]  # printing the last element of the row

3

In [95]:
arr[1, 0, :][2]  # printing the last element of the row

3

In [96]:
arr[1, 0, :][::-1]   # printing the row in reverse

array([3, 2, 1])

In [97]:
arr[2, 1, 1:]

array([5, 6])

In [98]:
arr[:,0,:]  # printing only the first rows

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [99]:
arr1 = np.random.random((3,2))

In [100]:
arr1

array([[0.68944117, 0.63287022],
       [0.73312921, 0.51356272],
       [0.23870645, 0.05730959]])

In [101]:
arr1.T   

array([[0.68944117, 0.73312921, 0.23870645],
       [0.63287022, 0.51356272, 0.05730959]])

In [102]:
arr2 = np.random.random((3,2))

In [103]:
arr2

array([[0.83885737, 0.82794001],
       [0.14198919, 0.85170138],
       [0.61467213, 0.653284  ]])

In [104]:
arr1.shape

(3, 2)

In [105]:
arr2.shape  # we can concatenate arr1 and arr2 as they have same shape

(3, 2)

In [106]:
np.concatenate((arr1,arr2))  # pass the tuple containing name of both tables

array([[0.68944117, 0.63287022],
       [0.73312921, 0.51356272],
       [0.23870645, 0.05730959],
       [0.83885737, 0.82794001],
       [0.14198919, 0.85170138],
       [0.61467213, 0.653284  ]])

In [107]:
np.concatenate((arr1,arr2), axis = 1)  # axis tells whether we want to concatenate horizontally and verically (0-> vertical, 1->horizontal)

array([[0.68944117, 0.63287022, 0.83885737, 0.82794001],
       [0.73312921, 0.51356272, 0.14198919, 0.85170138],
       [0.23870645, 0.05730959, 0.61467213, 0.653284  ]])

MATRIX OPERATIONS

In [108]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
arr + 5  # increaments each element by 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [110]:
arr -5  # decreases each element by 5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [111]:
arr*5  # mutiplies each element by 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [112]:
arr.sum() # sum of all elements

45

In [113]:
arr.mean()  # average of all elements

4.5

In [114]:
arr.min() # minimum element from the array

0

In [115]:
arr.max() # maximum element from the array

9

In [116]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
arr = np.array([2,2,2])
arr

array([2, 2, 2])

In [118]:
arr1 + arr  # adding 1-D array to the 2-D array

array([[3, 4, 5],
       [6, 7, 8]])

In [119]:
arr2 = np.array([[1,1,1],[2,2,2]])
arr2

array([[1, 1, 1],
       [2, 2, 2]])

In [120]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
arr1 + arr2 # adding two 2-D arrays

array([[2, 3, 4],
       [6, 7, 8]])

In [122]:
arr = np.array([4,6,7,1,8])

arr

array([4, 6, 7, 1, 8])

In [123]:
arr.argsort()  # it shows the index in sorted positions

array([3, 0, 1, 2, 4], dtype=int64)

In [124]:
arr.argmin()  # returns the index of the minimum element

3

In [126]:
arr.argmax() # return the index of the maximum element

4