## NUMPY

In [118]:
import numpy as np


In [119]:
lst = [25,41,23,54,11.2]
arr = np.array(lst)   ## passing a list
arr


array([25. , 41. , 23. , 54. , 11.2])

In [120]:
arr

array([25. , 41. , 23. , 54. , 11.2])

In [121]:
print(type(arr))

<class 'numpy.ndarray'>


In [122]:
arr.dtype


dtype('float64')

In [123]:
lst = [25,41.63,89,78,58.2,85,52]


In [124]:
arr = np.array(lst)

## to maintain homogenity of the array, the data type all other element is changed when yhat of one element is changed 

In [125]:
arr

array([25.  , 41.63, 89.  , 78.  , 58.2 , 85.  , 52.  ])

In [126]:
arr.dtype

dtype('float64')

In [127]:
arr


array([25.  , 41.63, 89.  , 78.  , 58.2 , 85.  , 52.  ])

In [128]:
arr[2]

89.0

In [129]:
arr[-3]

58.2

In [130]:
arr[2:4]

array([89., 78.])

In [131]:
arr[:]  # will print complete array

array([25.  , 41.63, 89.  , 78.  , 58.2 , 85.  , 52.  ])

In [132]:
arr[::]

array([25.  , 41.63, 89.  , 78.  , 58.2 , 85.  , 52.  ])

In [133]:
arr[::-1]

array([52.  , 85.  , 58.2 , 78.  , 89.  , 41.63, 25.  ])

In [134]:
arr[-1:-3:-1]

array([52., 85.])

In [135]:
arr.ndim        # tells the number of dimensions of the array

1

In [136]:
np.arange(20) # creates a list from range(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [137]:
np.zeros(10)  # creates an array of 10 elements all zeros, takes by default float value, used to create dummy arrays

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [138]:
np.ones(10)  # creates an array of 10 elements all ones, takes by default float value, used to create dummy arrays

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [139]:
np.linspace(1,5,10)  # creates an array from range 1 to 5 with 10 elements, create float values

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

## 2D Array


In [140]:
arr2 = np.array([[11,12,13],[21,22,23],[31,32,33]])

In [141]:
arr2

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [142]:
arr2.ndim   # return 2 as the array is 2 dimensional

2

In [143]:
arr2.shape

(3, 3)

In [144]:
arr2

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [145]:
arr2[0]   # returns 0th row

array([11, 12, 13])

In [146]:
arr2[1][2]

23

In [147]:
arr2[0:2]

array([[11, 12, 13],
       [21, 22, 23]])

In [148]:
arr2[1:3,1:3]  #slicing -> [row,column]         Start : end : step_count

array([[22, 23],
       [32, 33]])

In [149]:
arr2[2][2]

33

In [150]:
arr2[-1,-1]

33

In [151]:
arr2[2,2]

33

In [152]:
arr3 = np.arange(60)  # creates one dimensional array
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [153]:
arr3 = np.arange(60).reshape(12,5)  # changes the 1-D array to 2-D array in 12 rows and 5 columns
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [154]:
arr3.ravel()  # changes the 2-D array into 1-D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [155]:
arr3.flatten()   # changes the 2-D array into 1-D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [156]:
arr4 = np.random.random(10)

In [157]:
arr4

array([0.63058563, 0.75006894, 0.38164779, 0.2249891 , 0.77799871,
       0.42012335, 0.12882223, 0.53248076, 0.05573917, 0.82834249])

In [158]:
arr4 = np.random.random((10,2))

In [170]:
arr4

array([[0.32906498, 0.22028241],
       [0.22831842, 0.93004304],
       [0.03115606, 0.84149697],
       [0.29797402, 0.60944204],
       [0.39992269, 0.72409285],
       [0.67759048, 0.68925038],
       [0.46322222, 0.99371978],
       [0.83430194, 0.84330572],
       [0.75427458, 0.17679227],
       [0.87280638, 0.35157706]])

In [160]:
arr5 = np.random.randint(1,5,10)  # creates an array of 10 elements within range(1,5) with integer values

In [161]:
arr5

array([1, 1, 1, 3, 2, 3, 3, 3, 2, 3])

In [162]:
arr5[-1] = 100

In [163]:
arr5

array([  1,   1,   1,   3,   2,   3,   3,   3,   2, 100])

In [164]:
arr = np.random.randint(1,200,200)

In [165]:
arr

array([ 59,  64, 197,  20,  96, 161, 188, 197, 113, 156,  91, 169,  74,
       141,  15, 184, 162,   2,  55,  67, 134,   7,  79,  57, 147,  47,
         2,   9,  21,  66,  66,   4, 160, 122, 125,  26,  30, 117,  81,
        66, 113,  78, 112,   8,   8, 139, 144, 155,  92, 142, 148,  70,
        55,  48, 134, 147, 107, 165, 108, 174,   7,  97,  17, 172, 115,
       169, 184,  54,  69, 113, 161, 123,  58,  57, 184,   5,  85, 133,
       139, 175, 169,  93, 145,  60,  78,  76, 178,  30, 113, 199,  71,
       191, 189, 180,  44,  12, 129,  96,  66,  80,  33,  65, 107, 138,
         7, 159, 134,   3,  15,  48,  41, 162, 169, 193,  63,  83,  17,
        67,  70, 128, 187, 134, 195, 187, 196, 197,  51, 196, 129, 128,
       101,  56, 149,  21, 153,  98,   3,  63, 105, 165, 112,  53, 151,
        56,  69, 161, 121,  91,  41, 138, 189,  27,  49, 115, 139,  71,
        50,  81,   5, 157, 133, 191, 118,  26,  52,  37, 185,  59, 188,
        43, 115, 111,  74,  34,  29, 127, 170, 165,  32, 196,  7

In [166]:
count = 0
for i in arr:
    if i<100:
        count+=1

print(count)

98


In [169]:
lst = [i for i in arr if i<100]
print(len(lst))

98
