Create a numpy array with filling random values, and shape of array
should be (12,5), and pass this array from a user-defined function, and
function should be able to return average, minimum, maximum, and
no. of evens in your last row. 

In [26]:
import numpy as np

In [27]:
arr = np.random.randint(1,100,60)

In [28]:
arr

array([32, 30, 29, 69, 34, 78, 11, 44, 28, 68, 81,  2, 38, 72, 88, 66, 64,
       21, 71, 57, 38, 75, 65, 34, 38, 38, 89, 35,  7, 40, 87, 17, 70, 24,
       85,  6, 10, 73, 36, 25, 64, 73, 56, 85,  5, 31, 19, 51,  1, 67, 97,
       84, 38, 89, 34, 52, 22, 95, 83, 51])

In [29]:
arr = arr.reshape(12,5)

In [30]:
arr

array([[32, 30, 29, 69, 34],
       [78, 11, 44, 28, 68],
       [81,  2, 38, 72, 88],
       [66, 64, 21, 71, 57],
       [38, 75, 65, 34, 38],
       [38, 89, 35,  7, 40],
       [87, 17, 70, 24, 85],
       [ 6, 10, 73, 36, 25],
       [64, 73, 56, 85,  5],
       [31, 19, 51,  1, 67],
       [97, 84, 38, 89, 34],
       [52, 22, 95, 83, 51]])

In [34]:
def array_func(arr):
    last_row = arr[-1]

    # max and min element

    max = last_row[0]
    min = last_row[0]
    for n in last_row:
        if n>max:
            max=n
        if n<min:
            min=n

    # Average
     
    avg = last_row.sum() / len(last_row)

    # No. of evens
    
    even = 0
    for i in last_row:
        if i%2 == 0:
            even+=1

    return (max,min, avg, even)

data = array_func(arr)
print(f'Last row of array : {arr[-1]}')
print(f'Max in last row : {data[0]}')
print(f'Min in last row : {data[1]}')
print(f'Average of elements in last row : {data[2]}')
print(f'No. of evens in last row : {data[3]}')
    

Last row of array : [52 22 95 83 51]
Max in last row : 95
Min in last row : 22
Average of elements in last row : 60.6
No. of evens in last row : 2


Let’s consider we have an array, e.g.
[[1 2 3 ],
[4 5 6 ],
[7 8 9 ]]
And apply slicing techniques to get reversed order elements of all the rows,
like this -> [[3 2 1],
 [6 5 4],
 [9 8 7]]

In [32]:

arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr1[:,::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])